/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SanityImageAssetReference = {
 _ref: string;
 _type: "reference";
 _weak?: boolean;
 [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
 _id: string;
 _type: "project";
 _createdAt: string;
 _updatedAt: string;
 _rev: string;
 id?: string;
 title?: string;
 type?:
  | "desktop app"
  | "web app"
  | "mobile app"
  | "cross-device app"
  | "machine learning"
  | "game"
  | "cli"
  | "api"
  | "compiler"
  | "graphics"
  | "security"
  | "network"
  | "hardware"
  | "robotics";
 blurb?: string;
 description?: string;
 longDescription?: string;
 stage?: "dev" | "released" | "deprecated";
 techStack?: Array<
  | "airflow"
  | "airtable"
  | "angular"
  | "ansible"
  | "anthropic"
  | "astro"
  | "babel"
  | "blazor"
  | "bootstrap"
  | "bun"
  | "c"
  | "c#"
  | "c++"
  | "clojure"
  | "cloudflare"
  | "confluence"
  | "dart"
  | "databricks"
  | "digitalocean"
  | "django"
  | "docker"
  | "elasticsearch"
  | "electron"
  | "elixir"
  | "erlang"
  | "excel"
  | "expo"
  | "express"
  | "express.js"
  | "fastapi"
  | "figma"
  | "firebase"
  | "flask"
  | "flutter"
  | "framer"
  | "gatsby"
  | "gcp"
  | "git"
  | "github"
  | "gitlab"
  | "go"
  | "graphql"
  | "hadoop"
  | "haskell"
  | "hasura"
  | "hugging face"
  | "java"
  | "javascript"
  | "jenkins"
  | "jest"
  | "jira"
  | "jquery"
  | "jupyter"
  | "kafka"
  | "kotlin"
  | "kubernetes"
  | "langchain"
  | "laravel"
  | "linear"
  | "linux"
  | "mariadb"
  | "material ui"
  | "mongodb"
  | "mui"
  | "mysql"
  | "neovim"
  | "nestjs"
  | "netlify"
  | "next.js"
  | "nextjs"
  | "nginx"
  | "node.js"
  | "nodejs"
  | "notion"
  | "numpy"
  | "openjdk"
  | "pandas"
  | "perplexity"
  | "php"
  | "postgresql"
  | "postman"
  | "prisma"
  | "python"
  | "pytorch"
  | "r"
  | "rabbitmq"
  | "react"
  | "react native"
  | "react router"
  | "react.js"
  | "reactjs"
  | "redis"
  | "redux"
  | "remix"
  | "rstudio"
  | "ruby"
  | "ruby on rails"
  | "rust"
  | "sanity"
  | "sass"
  | "scala"
  | "shadcn"
  | "shopify"
  | "sklearn"
  | "snowflake"
  | "socket.io"
  | "spark"
  | "springboot"
  | "sql"
  | "sqlite"
  | "storybook"
  | "supabase"
  | "svelte"
  | "swift"
  | "tailwind"
  | "tailwind css"
  | "tailwindcss"
  | "tensorflow"
  | "terraform"
  | "three.js"
  | "trello"
  | "typescript"
  | "ubuntu"
  | "unity"
  | "unreal engine"
  | "vercel"
  | "vim"
  | "vite"
  | "vitest"
  | "vue"
  | "vue.js"
  | "vuejs"
  | "webflow"
  | "webpack"
  | "wordpress"
  | "xcode"
 >;
 experience?: "ai-4-earth" | "comdel-internship";
 links?: {
  web?: string;
  ios?: string;
  android?: string;
  other?: string;
 };
 github?: string;
 startDate?: string;
 releaseDate?: string;
 deprecationDate?: string;
 logo?: {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
 };
 img?: {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
 };
};

export type SanityImageCrop = {
 _type: "sanity.imageCrop";
 top?: number;
 bottom?: number;
 left?: number;
 right?: number;
};

export type SanityImageHotspot = {
 _type: "sanity.imageHotspot";
 x?: number;
 y?: number;
 height?: number;
 width?: number;
};

export type Experience = {
 _id: string;
 _type: "experience";
 _createdAt: string;
 _updatedAt: string;
 _rev: string;
 id?: string;
 title?: string;
 position?: string;
 type?: "college" | "research" | "work" | "volunteer";
 blurb?: string;
 description?: string;
 longDescription?: string;
 status?: "current" | "former";
 projects?: Array<
  "pack-tracker" | "pps-kitting-shipments" | "personal-portfolio" | "statt"
 >;
 startDate?: string;
 endDate?: string;
 logo?: {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
 };
};

export type SanityImagePaletteSwatch = {
 _type: "sanity.imagePaletteSwatch";
 background?: string;
 foreground?: string;
 population?: number;
 title?: string;
};

export type SanityImagePalette = {
 _type: "sanity.imagePalette";
 darkMuted?: SanityImagePaletteSwatch;
 lightVibrant?: SanityImagePaletteSwatch;
 darkVibrant?: SanityImagePaletteSwatch;
 vibrant?: SanityImagePaletteSwatch;
 dominant?: SanityImagePaletteSwatch;
 lightMuted?: SanityImagePaletteSwatch;
 muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
 _type: "sanity.imageDimensions";
 height?: number;
 width?: number;
 aspectRatio?: number;
};

export type SanityImageMetadata = {
 _type: "sanity.imageMetadata";
 location?: Geopoint;
 dimensions?: SanityImageDimensions;
 palette?: SanityImagePalette;
 lqip?: string;
 blurHash?: string;
 thumbHash?: string;
 hasAlpha?: boolean;
 isOpaque?: boolean;
};

export type SanityFileAsset = {
 _id: string;
 _type: "sanity.fileAsset";
 _createdAt: string;
 _updatedAt: string;
 _rev: string;
 originalFilename?: string;
 label?: string;
 title?: string;
 description?: string;
 altText?: string;
 sha1hash?: string;
 extension?: string;
 mimeType?: string;
 size?: number;
 assetId?: string;
 uploadId?: string;
 path?: string;
 url?: string;
 source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
 _type: "sanity.assetSourceData";
 name?: string;
 id?: string;
 url?: string;
};

export type SanityImageAsset = {
 _id: string;
 _type: "sanity.imageAsset";
 _createdAt: string;
 _updatedAt: string;
 _rev: string;
 originalFilename?: string;
 label?: string;
 title?: string;
 description?: string;
 altText?: string;
 sha1hash?: string;
 extension?: string;
 mimeType?: string;
 size?: number;
 assetId?: string;
 uploadId?: string;
 path?: string;
 url?: string;
 metadata?: SanityImageMetadata;
 source?: SanityAssetSourceData;
};

export type Geopoint = {
 _type: "geopoint";
 lat?: number;
 lng?: number;
 alt?: number;
};

export type Slug = {
 _type: "slug";
 current?: string;
 source?: string;
};

export type AllSanitySchemaTypes =
 | SanityImageAssetReference
 | Project
 | SanityImageCrop
 | SanityImageHotspot
 | Experience
 | SanityImagePaletteSwatch
 | SanityImagePalette
 | SanityImageDimensions
 | SanityImageMetadata
 | SanityFileAsset
 | SanityAssetSourceData
 | SanityImageAsset
 | Geopoint
 | Slug;

// Source: sanity/lib/queries/experience.ts
// Variable: EXPERIENCES_QUERY
// Query: *[_type == "experience"]    | order(      title desc    ) {      _id,  id,  title,  position,  type,  blurb,  description,  longDescription,  status,  projects,  startDate,  endDate,  "logo": logo.asset->url,  }
export type EXPERIENCES_QUERY_RESULT = Array<{
 _id: string;
 id: string | null;
 title: string | null;
 position: string | null;
 type: "college" | "research" | "volunteer" | "work" | null;
 blurb: string | null;
 description: string | null;
 longDescription: string | null;
 status: "current" | "former" | null;
 projects: Array<
  "pack-tracker" | "personal-portfolio" | "pps-kitting-shipments" | "statt"
 > | null;
 startDate: string | null;
 endDate: string | null;
 logo: string | null;
}>;

// Source: sanity/lib/queries/experience.ts
// Variable: EXPERIENCE_BY_IDENTIFIER_QUERY
// Query: *[    _type == "experience" &&    (      lower(id) == $identifier    )  ][0] {      _id,  id,  title,  position,  type,  blurb,  description,  longDescription,  status,  projects,  startDate,  endDate,  "logo": logo.asset->url,  }
export type EXPERIENCE_BY_IDENTIFIER_QUERY_RESULT = {
 _id: string;
 id: string | null;
 title: string | null;
 position: string | null;
 type: "college" | "research" | "volunteer" | "work" | null;
 blurb: string | null;
 description: string | null;
 longDescription: string | null;
 status: "current" | "former" | null;
 projects: Array<
  "pack-tracker" | "personal-portfolio" | "pps-kitting-shipments" | "statt"
 > | null;
 startDate: string | null;
 endDate: string | null;
 logo: string | null;
} | null;

// Source: sanity/lib/queries/experience.ts
// Variable: EXPERIENCE_IDENTIFIERS_QUERY
// Query: *[_type == "experience"].id
export type EXPERIENCE_IDENTIFIERS_QUERY_RESULT = Array<string | null>;

// Source: sanity/lib/queries/project.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"]    | order(      title desc    ) {      _id,  id,  title,  type,  blurb,  description,  longDescription,  stage,  techStack,  experience,  links {    web,    ios,    android,    other  },  github,  startDate,  releaseDate,  deprecationDate,  "logo": logo.asset->url,  img  }
export type PROJECTS_QUERY_RESULT = Array<{
 _id: string;
 id: string | null;
 title: string | null;
 type:
  | "api"
  | "cli"
  | "compiler"
  | "cross-device app"
  | "desktop app"
  | "game"
  | "graphics"
  | "hardware"
  | "machine learning"
  | "mobile app"
  | "network"
  | "robotics"
  | "security"
  | "web app"
  | null;
 blurb: string | null;
 description: string | null;
 longDescription: string | null;
 stage: "deprecated" | "dev" | "released" | null;
 techStack: Array<
  | "airflow"
  | "airtable"
  | "angular"
  | "ansible"
  | "anthropic"
  | "astro"
  | "babel"
  | "blazor"
  | "bootstrap"
  | "bun"
  | "c"
  | "c#"
  | "c++"
  | "clojure"
  | "cloudflare"
  | "confluence"
  | "dart"
  | "databricks"
  | "digitalocean"
  | "django"
  | "docker"
  | "elasticsearch"
  | "electron"
  | "elixir"
  | "erlang"
  | "excel"
  | "expo"
  | "express.js"
  | "express"
  | "fastapi"
  | "figma"
  | "firebase"
  | "flask"
  | "flutter"
  | "framer"
  | "gatsby"
  | "gcp"
  | "git"
  | "github"
  | "gitlab"
  | "go"
  | "graphql"
  | "hadoop"
  | "haskell"
  | "hasura"
  | "hugging face"
  | "java"
  | "javascript"
  | "jenkins"
  | "jest"
  | "jira"
  | "jquery"
  | "jupyter"
  | "kafka"
  | "kotlin"
  | "kubernetes"
  | "langchain"
  | "laravel"
  | "linear"
  | "linux"
  | "mariadb"
  | "material ui"
  | "mongodb"
  | "mui"
  | "mysql"
  | "neovim"
  | "nestjs"
  | "netlify"
  | "next.js"
  | "nextjs"
  | "nginx"
  | "node.js"
  | "nodejs"
  | "notion"
  | "numpy"
  | "openjdk"
  | "pandas"
  | "perplexity"
  | "php"
  | "postgresql"
  | "postman"
  | "prisma"
  | "python"
  | "pytorch"
  | "r"
  | "rabbitmq"
  | "react native"
  | "react router"
  | "react.js"
  | "react"
  | "reactjs"
  | "redis"
  | "redux"
  | "remix"
  | "rstudio"
  | "ruby on rails"
  | "ruby"
  | "rust"
  | "sanity"
  | "sass"
  | "scala"
  | "shadcn"
  | "shopify"
  | "sklearn"
  | "snowflake"
  | "socket.io"
  | "spark"
  | "springboot"
  | "sql"
  | "sqlite"
  | "storybook"
  | "supabase"
  | "svelte"
  | "swift"
  | "tailwind css"
  | "tailwind"
  | "tailwindcss"
  | "tensorflow"
  | "terraform"
  | "three.js"
  | "trello"
  | "typescript"
  | "ubuntu"
  | "unity"
  | "unreal engine"
  | "vercel"
  | "vim"
  | "vite"
  | "vitest"
  | "vue.js"
  | "vue"
  | "vuejs"
  | "webflow"
  | "webpack"
  | "wordpress"
  | "xcode"
 > | null;
 experience: "ai-4-earth" | "comdel-internship" | null;
 links: {
  web: string | null;
  ios: string | null;
  android: string | null;
  other: string | null;
 } | null;
 github: string | null;
 startDate: string | null;
 releaseDate: string | null;
 deprecationDate: string | null;
 logo: string | null;
 img: {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
 } | null;
}>;

// Source: sanity/lib/queries/project.ts
// Variable: PROJECT_BY_IDENTIFIER_QUERY
// Query: *[    _type == "project" &&    (      lower(id) == $identifier    )  ][0] {      _id,  id,  title,  type,  blurb,  description,  longDescription,  stage,  techStack,  experience,  links {    web,    ios,    android,    other  },  github,  startDate,  releaseDate,  deprecationDate,  "logo": logo.asset->url,  img  }
export type PROJECT_BY_IDENTIFIER_QUERY_RESULT = {
 _id: string;
 id: string | null;
 title: string | null;
 type:
  | "api"
  | "cli"
  | "compiler"
  | "cross-device app"
  | "desktop app"
  | "game"
  | "graphics"
  | "hardware"
  | "machine learning"
  | "mobile app"
  | "network"
  | "robotics"
  | "security"
  | "web app"
  | null;
 blurb: string | null;
 description: string | null;
 longDescription: string | null;
 stage: "deprecated" | "dev" | "released" | null;
 techStack: Array<
  | "airflow"
  | "airtable"
  | "angular"
  | "ansible"
  | "anthropic"
  | "astro"
  | "babel"
  | "blazor"
  | "bootstrap"
  | "bun"
  | "c"
  | "c#"
  | "c++"
  | "clojure"
  | "cloudflare"
  | "confluence"
  | "dart"
  | "databricks"
  | "digitalocean"
  | "django"
  | "docker"
  | "elasticsearch"
  | "electron"
  | "elixir"
  | "erlang"
  | "excel"
  | "expo"
  | "express.js"
  | "express"
  | "fastapi"
  | "figma"
  | "firebase"
  | "flask"
  | "flutter"
  | "framer"
  | "gatsby"
  | "gcp"
  | "git"
  | "github"
  | "gitlab"
  | "go"
  | "graphql"
  | "hadoop"
  | "haskell"
  | "hasura"
  | "hugging face"
  | "java"
  | "javascript"
  | "jenkins"
  | "jest"
  | "jira"
  | "jquery"
  | "jupyter"
  | "kafka"
  | "kotlin"
  | "kubernetes"
  | "langchain"
  | "laravel"
  | "linear"
  | "linux"
  | "mariadb"
  | "material ui"
  | "mongodb"
  | "mui"
  | "mysql"
  | "neovim"
  | "nestjs"
  | "netlify"
  | "next.js"
  | "nextjs"
  | "nginx"
  | "node.js"
  | "nodejs"
  | "notion"
  | "numpy"
  | "openjdk"
  | "pandas"
  | "perplexity"
  | "php"
  | "postgresql"
  | "postman"
  | "prisma"
  | "python"
  | "pytorch"
  | "r"
  | "rabbitmq"
  | "react native"
  | "react router"
  | "react.js"
  | "react"
  | "reactjs"
  | "redis"
  | "redux"
  | "remix"
  | "rstudio"
  | "ruby on rails"
  | "ruby"
  | "rust"
  | "sanity"
  | "sass"
  | "scala"
  | "shadcn"
  | "shopify"
  | "sklearn"
  | "snowflake"
  | "socket.io"
  | "spark"
  | "springboot"
  | "sql"
  | "sqlite"
  | "storybook"
  | "supabase"
  | "svelte"
  | "swift"
  | "tailwind css"
  | "tailwind"
  | "tailwindcss"
  | "tensorflow"
  | "terraform"
  | "three.js"
  | "trello"
  | "typescript"
  | "ubuntu"
  | "unity"
  | "unreal engine"
  | "vercel"
  | "vim"
  | "vite"
  | "vitest"
  | "vue.js"
  | "vue"
  | "vuejs"
  | "webflow"
  | "webpack"
  | "wordpress"
  | "xcode"
 > | null;
 experience: "ai-4-earth" | "comdel-internship" | null;
 links: {
  web: string | null;
  ios: string | null;
  android: string | null;
  other: string | null;
 } | null;
 github: string | null;
 startDate: string | null;
 releaseDate: string | null;
 deprecationDate: string | null;
 logo: string | null;
 img: {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
 } | null;
} | null;

// Source: sanity/lib/queries/project.ts
// Variable: PROJECT_IDENTIFIERS_QUERY
// Query: *[_type == "project"].id
export type PROJECT_IDENTIFIERS_QUERY_RESULT = Array<string | null>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
 interface SanityQueries {
  '\n  *[_type == "experience"]\n    | order(\n      title desc\n    ) {\n    \n  _id,\n  id,\n  title,\n  position,\n  type,\n  blurb,\n  description,\n  longDescription,\n  status,\n  projects,\n  startDate,\n  endDate,\n  "logo": logo.asset->url,\n\n  }\n': EXPERIENCES_QUERY_RESULT;
  '\n  *[\n    _type == "experience" &&\n    (\n      lower(id) == $identifier\n    )\n  ][0] {\n    \n  _id,\n  id,\n  title,\n  position,\n  type,\n  blurb,\n  description,\n  longDescription,\n  status,\n  projects,\n  startDate,\n  endDate,\n  "logo": logo.asset->url,\n\n  }\n': EXPERIENCE_BY_IDENTIFIER_QUERY_RESULT;
  '\n  *[_type == "experience"].id\n': EXPERIENCE_IDENTIFIERS_QUERY_RESULT;
  '\n  *[_type == "project"]\n    | order(\n      title desc\n    ) {\n    \n  _id,\n  id,\n  title,\n  type,\n  blurb,\n  description,\n  longDescription,\n  stage,\n  techStack,\n  experience,\n  links {\n    web,\n    ios,\n    android,\n    other\n  },\n  github,\n  startDate,\n  releaseDate,\n  deprecationDate,\n  "logo": logo.asset->url,\n  img\n\n  }\n': PROJECTS_QUERY_RESULT;
  '\n  *[\n    _type == "project" &&\n    (\n      lower(id) == $identifier\n    )\n  ][0] {\n    \n  _id,\n  id,\n  title,\n  type,\n  blurb,\n  description,\n  longDescription,\n  stage,\n  techStack,\n  experience,\n  links {\n    web,\n    ios,\n    android,\n    other\n  },\n  github,\n  startDate,\n  releaseDate,\n  deprecationDate,\n  "logo": logo.asset->url,\n  img\n\n  }\n': PROJECT_BY_IDENTIFIER_QUERY_RESULT;
  '\n  *[_type == "project"].id\n': PROJECT_IDENTIFIERS_QUERY_RESULT;
 }
}
